apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: mynginx

spec:
  containers:
  - name: nginx
    image: nginx:1.15.2

  tolerations:
  - key: node-type
    value: production
    operator: Equal
    effect: NoSchedule

