apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
  # 管理dev名称空间下pod的网络
  namespace: dev
spec:
  podSelector: {}
  # 明确指定管理入栈网络，如果入栈网络不指明，表示禁止所有入栈网络
  policyTypes: ["Ingress"]
