# ---------------------- Deployment 资源 ------------------------- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.2
        ports:
        - name: nginx
          containerPort: 80
        resources:
          requests:
            cpu: 1m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 100Mi

---

# ---------------------- Service资源 ------------------------- 
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-np
spec:
  selector:
    app: nginx
    tier: frontend
  type: NodePort
  ports: 
  - name: nginx-ports
    port: 80
    targetPort: 80
    nodePort: 30088

---

# ---------------------- HPA 资源 -------------------------
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  labels:
    project: nginx-pod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-dm
  minReplicas: 1
  maxReplicas: 10
  # autoscaling/v1群组，根据CPU资源使用情况去度量
  # targetCPUUtilizationPercentage: 66

  # autoscaling/v2beta1群组，根据CPU、内存资源使用情况去度量
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 66
  - type: Resource
    resource:
      name: memory
      targetAverageValue: 66Mi
